spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tzdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username:  ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

app:
  jwt:
    secret: changeme-secret-key
    expiration: 3600000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
